"""create M0 domain baseline

Revision ID: bde94e64f993
Revises:
Create Date: 2026-09-04 13:37:44.896322
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "bde94e64f993"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=128), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
        sa.UniqueConstraint("slug", name=op.f("uq_organizations_slug")),
    )
    op.create_table(
        "standards",
        sa.Column("code", sa.String(length=128), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("jurisdiction", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_standards")),
        sa.UniqueConstraint("code", name=op.f("uq_standards_code")),
    )
    op.create_table(
        "projects",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("code", sa.String(length=128), nullable=True),
        sa.Column("jurisdiction", sa.String(length=255), nullable=True),
        sa.Column("design_date", sa.Date(), nullable=True),
        sa.Column("building_type", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_projects_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
        sa.UniqueConstraint("organization_id", "code", name="uq_projects_organization_code"),
    )
    op.create_index(
        op.f("ix_projects_organization_id"), "projects", ["organization_id"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_users_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_index(op.f("ix_users_organization_id"), "users", ["organization_id"], unique=False)
    op.create_table(
        "audit_events",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=255), nullable=False),
        sa.Column("entity_type", sa.String(length=128), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column("request_id", sa.String(length=128), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["users.id"], name=op.f("fk_audit_events_actor_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_audit_events_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_index(op.f("ix_audit_events_actor_id"), "audit_events", ["actor_id"], unique=False)
    op.create_index(op.f("ix_audit_events_entity_id"), "audit_events", ["entity_id"], unique=False)
    op.create_index(
        op.f("ix_audit_events_occurred_at"), "audit_events", ["occurred_at"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_organization_id"), "audit_events", ["organization_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_request_id"), "audit_events", ["request_id"], unique=False
    )
    op.create_table(
        "jobs",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("job_type", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("input_data", sa.JSON(), nullable=False),
        sa.Column("output_data", sa.JSON(), nullable=True),
        sa.Column("error_data", sa.JSON(), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_jobs_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_jobs_project_id_projects")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
    )
    op.create_index(op.f("ix_jobs_organization_id"), "jobs", ["organization_id"], unique=False)
    op.create_index(op.f("ix_jobs_project_id"), "jobs", ["project_id"], unique=False)
    op.create_table(
        "project_facts",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("unit", sa.String(length=64), nullable=True),
        sa.Column("scope_data", sa.JSON(), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("verification_status", sa.String(length=64), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("extractor_version", sa.String(length=128), nullable=True),
        sa.Column("supersedes_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_project_facts_project_id_projects")
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_id"],
            ["project_facts.id"],
            name=op.f("fk_project_facts_supersedes_id_project_facts"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_facts")),
    )
    op.create_index(op.f("ix_project_facts_key"), "project_facts", ["key"], unique=False)
    op.create_index(
        op.f("ix_project_facts_project_id"), "project_facts", ["project_id"], unique=False
    )
    op.create_index(
        "ix_project_facts_project_key", "project_facts", ["project_id", "key"], unique=False
    )
    op.create_table(
        "project_files",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("logical_name", sa.String(length=512), nullable=False),
        sa.Column("purpose", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_project_files_project_id_projects")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_files")),
    )
    op.create_index(
        op.f("ix_project_files_project_id"), "project_files", ["project_id"], unique=False
    )
    op.create_table(
        "review_packages",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("project_snapshot_hash", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_review_packages_project_id_projects")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_packages")),
    )
    op.create_index(
        op.f("ix_review_packages_project_id"), "review_packages", ["project_id"], unique=False
    )
    op.create_table(
        "check_runs",
        sa.Column("review_package_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("project_snapshot", sa.JSON(), nullable=False),
        sa.Column("rule_pack_snapshot", sa.JSON(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["review_package_id"],
            ["review_packages.id"],
            name=op.f("fk_check_runs_review_package_id_review_packages"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_check_runs")),
    )
    op.create_index(
        op.f("ix_check_runs_review_package_id"), "check_runs", ["review_package_id"], unique=False
    )
    op.create_table(
        "file_versions",
        sa.Column("project_file_id", sa.Uuid(), nullable=True),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("original_filename", sa.String(length=512), nullable=False),
        sa.Column("media_type", sa.String(length=255), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("object_key", sa.String(length=1024), nullable=False),
        sa.Column("uploaded_by_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_file_id"],
            ["project_files.id"],
            name=op.f("fk_file_versions_project_file_id_project_files"),
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_id"], ["users.id"], name=op.f("fk_file_versions_uploaded_by_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_file_versions")),
        sa.UniqueConstraint("object_key", name=op.f("uq_file_versions_object_key")),
        sa.UniqueConstraint(
            "project_file_id", "version_number", name="uq_file_versions_file_version_number"
        ),
    )
    op.create_index(
        op.f("ix_file_versions_project_file_id"), "file_versions", ["project_file_id"], unique=False
    )
    op.create_index(op.f("ix_file_versions_sha256"), "file_versions", ["sha256"], unique=False)
    op.create_table(
        "standard_versions",
        sa.Column("standard_id", sa.Uuid(), nullable=False),
        sa.Column("edition", sa.String(length=128), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=True),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("lifecycle_status", sa.String(length=64), nullable=False),
        sa.Column("source_file_version_id", sa.Uuid(), nullable=False),
        sa.Column("document_hash", sa.String(length=64), nullable=False),
        sa.Column("supersedes_id", sa.Uuid(), nullable=True),
        sa.Column("parser_version", sa.String(length=128), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_file_version_id"],
            ["file_versions.id"],
            name=op.f("fk_standard_versions_source_file_version_id_file_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["standard_id"],
            ["standards.id"],
            name=op.f("fk_standard_versions_standard_id_standards"),
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_id"],
            ["standard_versions.id"],
            name=op.f("fk_standard_versions_supersedes_id_standard_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_standard_versions")),
        sa.UniqueConstraint("standard_id", "edition", name="uq_standard_versions_edition"),
    )
    op.create_index(
        op.f("ix_standard_versions_standard_id"), "standard_versions", ["standard_id"], unique=False
    )
    op.create_table(
        "clauses",
        sa.Column("standard_version_id", sa.Uuid(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("clause_number", sa.String(length=128), nullable=False),
        sa.Column("heading", sa.String(length=512), nullable=True),
        sa.Column("original_text", sa.Text(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("bounding_box", sa.JSON(), nullable=True),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("lifecycle_status", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["clauses.id"], name=op.f("fk_clauses_parent_id_clauses")
        ),
        sa.ForeignKeyConstraint(
            ["standard_version_id"],
            ["standard_versions.id"],
            name=op.f("fk_clauses_standard_version_id_standard_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clauses")),
        sa.UniqueConstraint(
            "standard_version_id", "clause_number", name="uq_clauses_standard_version_number"
        ),
    )
    op.create_index(
        "ix_clauses_standard_order", "clauses", ["standard_version_id", "order_index"], unique=False
    )
    op.create_index(
        op.f("ix_clauses_standard_version_id"), "clauses", ["standard_version_id"], unique=False
    )
    op.create_table(
        "rule_packs",
        sa.Column("standard_version_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("semantic_version", sa.String(length=32), nullable=False),
        sa.Column("lifecycle_status", sa.String(length=64), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["standard_version_id"],
            ["standard_versions.id"],
            name=op.f("fk_rule_packs_standard_version_id_standard_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rule_packs")),
        sa.UniqueConstraint(
            "standard_version_id", "semantic_version", name="uq_rule_packs_standard_version_semver"
        ),
    )
    op.create_index(
        op.f("ix_rule_packs_standard_version_id"),
        "rule_packs",
        ["standard_version_id"],
        unique=False,
    )
    op.create_table(
        "evidence",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_fact_id", sa.Uuid(), nullable=True),
        sa.Column("clause_id", sa.Uuid(), nullable=True),
        sa.Column("file_version_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("location", sa.JSON(), nullable=False),
        sa.Column("excerpt", sa.Text(), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["clause_id"], ["clauses.id"], name=op.f("fk_evidence_clause_id_clauses")
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["users.id"], name=op.f("fk_evidence_created_by_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["file_version_id"],
            ["file_versions.id"],
            name=op.f("fk_evidence_file_version_id_file_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_evidence_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["project_fact_id"],
            ["project_facts.id"],
            name=op.f("fk_evidence_project_fact_id_project_facts"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence")),
    )
    op.create_index(op.f("ix_evidence_clause_id"), "evidence", ["clause_id"], unique=False)
    op.create_index(
        op.f("ix_evidence_file_version_id"), "evidence", ["file_version_id"], unique=False
    )
    op.create_index(
        op.f("ix_evidence_organization_id"), "evidence", ["organization_id"], unique=False
    )
    op.create_index(
        op.f("ix_evidence_project_fact_id"), "evidence", ["project_fact_id"], unique=False
    )
    op.create_table(
        "review_package_rule_packs",
        sa.Column("review_package_id", sa.Uuid(), nullable=False),
        sa.Column("rule_pack_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["review_package_id"],
            ["review_packages.id"],
            name=op.f("fk_review_package_rule_packs_review_package_id_review_packages"),
        ),
        sa.ForeignKeyConstraint(
            ["rule_pack_id"],
            ["rule_packs.id"],
            name=op.f("fk_review_package_rule_packs_rule_pack_id_rule_packs"),
        ),
        sa.PrimaryKeyConstraint(
            "review_package_id", "rule_pack_id", name=op.f("pk_review_package_rule_packs")
        ),
    )
    op.create_table(
        "rules",
        sa.Column("rule_pack_id", sa.Uuid(), nullable=False),
        sa.Column("source_clause_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("severity", sa.String(length=64), nullable=False),
        sa.Column("lifecycle_status", sa.String(length=64), nullable=False),
        sa.Column("applicability", sa.JSON(), nullable=False),
        sa.Column("inputs", sa.JSON(), nullable=False),
        sa.Column("expression", sa.JSON(), nullable=False),
        sa.Column("missing_data_status", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["rule_pack_id"], ["rule_packs.id"], name=op.f("fk_rules_rule_pack_id_rule_packs")
        ),
        sa.ForeignKeyConstraint(
            ["source_clause_id"], ["clauses.id"], name=op.f("fk_rules_source_clause_id_clauses")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rules")),
        sa.UniqueConstraint("rule_pack_id", "code", name="uq_rules_rule_pack_code"),
    )
    op.create_index(op.f("ix_rules_rule_pack_id"), "rules", ["rule_pack_id"], unique=False)
    op.create_index(op.f("ix_rules_source_clause_id"), "rules", ["source_clause_id"], unique=False)
    op.create_table(
        "check_results",
        sa.Column("check_run_id", sa.Uuid(), nullable=False),
        sa.Column("rule_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("severity", sa.String(length=64), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("fact_ids", sa.JSON(), nullable=False),
        sa.Column("regulation_evidence_ids", sa.JSON(), nullable=False),
        sa.Column("project_evidence_ids", sa.JSON(), nullable=False),
        sa.Column("trace", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["check_run_id"],
            ["check_runs.id"],
            name=op.f("fk_check_results_check_run_id_check_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["rule_id"], ["rules.id"], name=op.f("fk_check_results_rule_id_rules")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_check_results")),
        sa.UniqueConstraint("check_run_id", "rule_id", name="uq_check_results_run_rule"),
    )
    op.create_index(
        op.f("ix_check_results_check_run_id"), "check_results", ["check_run_id"], unique=False
    )
    op.create_index(op.f("ix_check_results_rule_id"), "check_results", ["rule_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_check_results_rule_id"), table_name="check_results")
    op.drop_index(op.f("ix_check_results_check_run_id"), table_name="check_results")
    op.drop_table("check_results")
    op.drop_index(op.f("ix_rules_source_clause_id"), table_name="rules")
    op.drop_index(op.f("ix_rules_rule_pack_id"), table_name="rules")
    op.drop_table("rules")
    op.drop_table("review_package_rule_packs")
    op.drop_index(op.f("ix_evidence_project_fact_id"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_organization_id"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_file_version_id"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_clause_id"), table_name="evidence")
    op.drop_table("evidence")
    op.drop_index(op.f("ix_rule_packs_standard_version_id"), table_name="rule_packs")
    op.drop_table("rule_packs")
    op.drop_index(op.f("ix_clauses_standard_version_id"), table_name="clauses")
    op.drop_index("ix_clauses_standard_order", table_name="clauses")
    op.drop_table("clauses")
    op.drop_index(op.f("ix_standard_versions_standard_id"), table_name="standard_versions")
    op.drop_table("standard_versions")
    op.drop_index(op.f("ix_file_versions_sha256"), table_name="file_versions")
    op.drop_index(op.f("ix_file_versions_project_file_id"), table_name="file_versions")
    op.drop_table("file_versions")
    op.drop_index(op.f("ix_check_runs_review_package_id"), table_name="check_runs")
    op.drop_table("check_runs")
    op.drop_index(op.f("ix_review_packages_project_id"), table_name="review_packages")
    op.drop_table("review_packages")
    op.drop_index(op.f("ix_project_files_project_id"), table_name="project_files")
    op.drop_table("project_files")
    op.drop_index("ix_project_facts_project_key", table_name="project_facts")
    op.drop_index(op.f("ix_project_facts_project_id"), table_name="project_facts")
    op.drop_index(op.f("ix_project_facts_key"), table_name="project_facts")
    op.drop_table("project_facts")
    op.drop_index(op.f("ix_jobs_project_id"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_organization_id"), table_name="jobs")
    op.drop_table("jobs")
    op.drop_index(op.f("ix_audit_events_request_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_organization_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_occurred_at"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_entity_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_actor_id"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index(op.f("ix_users_organization_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_projects_organization_id"), table_name="projects")
    op.drop_table("projects")
    op.drop_table("standards")
    op.drop_table("organizations")
    # ### end Alembic commands ###
